### ISSUE TITLE
Can't get correct article content if content in table, bug?

### ISSUE THREAD

**Issue by eromoe** [buriy/python-readability#76]
I have some urls on same site. 

Can't get corret contain(with table):
http://ecp.sgcc.com.cn/html/project/014002007/9990000000010135023.html
http://ecp.sgcc.com.cn/html/project/014001001/9900000000003560149.html

Work fine if no table:
http://ecp.sgcc.com.cn/html/news/014001008/7900000000000045486.html

Maybe a bug?

update:
I use `print doc.score_paragraphs()` see what happen:
```
{ < Element table at 0x50fb180 > : {
        'content_score': 1.95,
        'elem': < Element table at 0x50fb180 >
    },
    < Element tr at 0x5024b10 > : {
        'content_score': 2.0,
        'elem': < Element tr at 0x5024b10 >
    },
    < Element tr at 0x50fb300 > : {
        'content_score': 2.0,
        'elem': < Element tr at 0x50fb300 >
    }
}
```

I think tag with `tr` and `td` shoud not be treat as candidate, beside they are under `table` which also should plus some score to their parent `table`.

**Comment by eromoe** [comment]
I find that due to many `td`'s `inner_text_len < MIN_LEN`, so table can't get a high score .

**Comment by buriy** [comment]
Algorithm is probabilistic, it won't get 100% sources correctly.
Advertising and input forms also use tables with short texts and images, so how one could assume the tables with short tests to have no advertising (and no user forms?
I remind you that this algorithm was created for articles processing, not for arbitrary text extraction.

**Comment by eromoe** [comment]
Could you explain 

> I remind you that this algorithm was created for articles processing, not for arbitrary text extraction.

I think `articles processing` means : get title and article main contain( this is I want ) .
But I don't understand `arbitrary text extraction`,  translate(use google translation) to Chinese means: random text extraction .

**Comment by buriy** [comment]
http://ecp.sgcc.com.cn/html/project/014002007/9990000000010135023.html
By "articles" , usually "news articles" are meant. This is a page, but not a news article (guessing from how it looks like, at least).
You might have a set of different rules for this kind of pages because the same set of rules won't work equally good for both.
But for year 2016, a better approach would be to use machine learning (of course if you have a big corpus) -- boosting trees (like ones made by xgboost) should help.
Otherwise, if you have just several sources, it's easier to set up the rules manually for each source: something like ".article" for source1, "div[1]/div[1]" for source2, etc.
The algorithm from this library is made only for quick news article extraction, to process maybe 90% of sources automatically, but others to be processed manually anyway.
If you will change the rules -- it will process different 90% of articles, but with any single set of rules you will never process all 100% of the articles correctly.
Manually or with machine learning methods, you can improve the score -- but only if you have a very big corpus.

**Comment by eromoe** [comment]
Ok, I understand, thank you !
