### ISSUE TITLE
Why not calculate node score from deep to shallow?

### ISSUE THREAD

**Issue by eromoe** [buriy/python-readability#78]
Default calculation is follow:

```
/div/p[1]
/div/div[1]/p[1]
/div/div[1]/div/p
/div/div[1]/div/div/p[1]
/div/div[1]/div/div/p[2]
/div/div[1]/div/div/p[3]
/div/div[1]/p[2]
/div/div[1]/p[3]
/div/div[1]/p[4]
/div/div[1]/p[5]
/div/div[1]/p[6]
```

step 1. `/div/div[1]/p[1]` add score to `/div/div[1]` and `/div`

step 2. `/div/div[1]/div/p` add score to `/div/div[1]/div` and `/div/div[1]`

Score of `/div` doesn't change , but his child `/div/div[1]` score increased. 

I think it is not correct here, sort tags first would make score more accurate

**Comment by buriy** [comment]
I remember that this was made on purpose -- the algorithm sums up only scores of node children and grand-children, and so you can just correct coefficients instead of changing order of calculation.
You can complain to the author of the original algorithm.
Or you can make a huge test set collected from different article sources, and prove that he was wrong and you are right.

**Comment by eromoe** [comment]
Could you provide a test dataset ? 
My biggest problem is lack of data...

**Comment by buriy** [comment]
Sorry, I don't have a public dataset.
I had a small private dataset for my purposes earlier (~50 different sources).
But it's not enough for major changes in the algorithm -- only for fixing obvious mistakes that shouldn't hurt other pages.
